kind = "web"
previewPath = "/"
title = "Loshy ❤️"
version = "1.0.0"
id = "artifacts/loshy"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21924

[services.development]
run = "pnpm --filter @workspace/loshy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/loshy", "run", "build" ]
serve = "static"
publicDir = "artifacts/loshy/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21924"
BASE_PATH = "/"
